apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
  namespace: prod
spec:
  metrics:
    - name: success-rate
      interval: 15s
      count: 4
      successCondition: result[0] >= 0.9
      failureLimit: 2
      provider:
        prometheus:
          address: http://prometheus.monitoring.svc.cluster.local:9090
          query: |
            sum(rate(http_requests_total{status="200"}[1m]))
            /
            sum(rate(http_requests_total[1m]))
