apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
  namespace: prod
spec:
  args:
    - name: canaryHash
  metrics:
    - name: success-rate
      interval: 20s
      count: 4
      successCondition: result[0] >= 0.7
      failureLimit: 2
      provider:
        prometheus:
          address: http://prometheus.monitoring.svc.cluster.local:9090
          query: |
            sum(rate(http_requests_total{status="200", pod_hash="{{args.canaryHash}}"}[2m]))
            /
            sum(rate(http_requests_total{pod_hash="{{args.canaryHash}}"}[2m]))
