apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-canary-app-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Hiba-Farah/gitops-canary-config.git
    targetRevision: main
    path: apps/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
