apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-canary-app
  namespace: staging
  labels:
    app: gitops-canary-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gitops-canary-app
  template:
    metadata:
      labels:
        app: gitops-canary-app
    spec:
      containers:
        - name: app
          image: ghcr.io/hiba-farah/gitops-canary-app:4a69284
          ports:
            - containerPort: 8000
          env:
            - name: APP_VERSION
              value: "v1"
            - name: FAIL_RATE
              value: "0"
